# MySQL 数据库配置
# 开发和测试环境使用本地 MySQL
# 生产环境使用阿里云 RDS
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: true
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: zheli_read_development

test:
  <<: *default
  database: zheli_read_test

production:
  <<: *default
  pool: <%= ENV.fetch("DATABASE_POOL_SIZE") { 100 } %>
  database: <%= ENV['DATABASE_PRD_DATABASE'] %>
  username: <%= ENV['DATABASE_PRD_USERNAME'] %>
  password: <%= ENV['DATABASE_PRD_PASSWORD'] %>
  host: <%= ENV['DATABASE_PRD_HOST'] %>
  port: <%= ENV['DATABASE_PRD_PORT'] || 3306 %>

staging:
  <<: *default
  pool: 20
  database: <%= ENV['DATABASE_DEV_DATABASE'] %>
  username: <%= ENV['DATABASE_DEV_USERNAME'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  host: <%= ENV['DATABASE_DEV_HOST'] %>
  port: <%= ENV['DATABASE_DEV_PORT'] %>